#!/usr/bin/env python

import random

class Die:
    @staticmethod
    def roll():
        return random.choice(("L", "R", "C", "*", "*", "*"))

class Player:
    num_chips = 0
    def __init__(self, name, num_chips):
        self.name = name
        self.num_chips = num_chips

    def transfer_chip_to(self, player):
        self.num_chips -= 1
        player.num_chips += 1

class Game:
    die = ("L", "R", "C", "*", "*", "*")
    starting_chips = 3

    def __init__(self, *player_names):
        self.players = []
        for player_name in player_names:
            self.players.append(Player(player_name, self.starting_chips))
        self.active_player_index = 0
        self.left_player_index = len(self.players) - 1
        self.right_player_index = 1
        self.center = Player("center", 0)

    def play_turn(self):
        number_of_rolls = min(self.players[self.active_player_index].num_chips, 3)
        active_player = self.players[self.active_player_index]
        left_player   = self.players[self.left_player_index]
        right_player  = self.players[self.right_player_index]

        for _ in range(number_of_rolls):
            # roll = random.choice(self.die)
            roll = Die.roll()

            print("{:7s}: chips: {}, roll: '{}'".format(active_player.name, active_player.num_chips, roll))

            if (roll == "L"):   # player to left gets 1 chip
                active_player.transfer_chip_to(left_player)
            elif (roll == "R"): # player to right gets 1 chip
                active_player.transfer_chip_to(right_player)
            elif (roll == "C"): # chip goes to the center
                active_player.transfer_chip_to(self.center)
            else:               # roll == "*" and do nothing
                pass

        self.rotate_active_player()

    def rotate_active_player(self):
        self.players = self.players[1:] + self.players[0:1]

    def game_over(self):
        # game is over when only one players has chips
        players_with_chips = 0
        for player in self.players:
            if player.num_chips > 0:
                players_with_chips += 1
        return players_with_chips == 1

    def find_winner(self):
        if not self.game_over():
            raise Exception("Can only have a winner when game is over.")

        for player in self.players:
            if player.num_chips > 0:
                return player

    def play(self):
        turn_count = 0
        max_turns = 10000
        while (not self.game_over()) and (turn_count < max_turns):
            self.play_turn()
            turn_count += 1
        print("Game over. The winner is {} in {} turns!".format(self.find_winner().name, turn_count))
        print("The center has {} chips.".format(self.center.num_chips))

# play the game
mygame = Game("Alice", "Bob", "Carol", "David")
mygame.play()
